# Use the official Nginx image as the base image
FROM nginx:latest

# Copy your static site files to the Nginx default directory
COPY ../dist/showcase/browser /usr/share/nginx/html

# Expose port 80 to allow traffic
EXPOSE 80

# Start Nginx
CMD ["nginx", "-g", "daemon off;"]