# Use the official Nginx image as the base image
FROM nginx:latest

# Copy your static site files to the Nginx default directory
COPY ../dist/apparel-top100-showcase /usr/share/nginx/html

# Copy custom Nginx configuration
COPY nginx.conf /etc/nginx/nginx.conf

# Expose port 80 to allow traffic
EXPOSE 80

# Start Nginx
CMD ["nginx", "-g", "daemon off;"]